### ISSUE TITLE
Caractères ayant 7 en p5 n'apparaissent pas sur les pétales. Ex: 39937500 Ling 领 ou 19397500 Yong颙

### ISSUE THREAD

**Issue by DeBaoren** [hypacosmos/hypa-android#5]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by shiipou** [comment]
Fix in release 9
