### ISSUE TITLE
Dans octogone les cercles apparaissent en grande taille alors qu'ils ne devraient apparaître qu'en petit sauf le cercle violet placé en 1 qui doit être grand QUE quand il y a un second floor. Ex: 91718915

### ISSUE THREAD

**Issue by DeBaoren** [hypacosmos/hypa-android#6]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by shiipou** [comment]
Fixed in release 8
